### ISSUE TITLE
Failed to load plugin after updating eslint-plugin-react

### ISSUE THREAD

**Issue by marklaihk01** [DianaSuvorova/eslint-plugin-react-redux#47]
after updating `eslint-plugin-react` to v7.18.0
the plugin failed to load with the following message

```
Failed to load plugin 'eslint-plugin-react-redux' declared in '.eslintrc.yml': Cannot find module 'es-abstract/2018/RequireObjectCoercible'
```

**Comment by ljharb** [comment]
Do you perhaps have a lockfile, and have you failed to update your transitive dependencies?
